"""create example_credentials

Revision ID: e25b5eb72101
Revises: 
Create Date: 2026-09-12 20:15:02.796995
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'e25b5eb72101'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('api_url', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('api_token', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer', 'instance_id', name='uq_example_credentials_tenant')
    )
    op.create_index(op.f('ix_example_credentials_customer'), 'example_credentials', ['customer'], unique=False)
    op.create_index(op.f('ix_example_credentials_instance_id'), 'example_credentials', ['instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_example_credentials_instance_id'), table_name='example_credentials')
    op.drop_index(op.f('ix_example_credentials_customer'), table_name='example_credentials')
    op.drop_table('example_credentials')
    # ### end Alembic commands ###
